export default {
  LOGIN: 'LOGIN',
  SIGN_OUT: 'SIGN_OUT',
  SET_AUTH: 'SET_AUTH',
  SIGNUP_REQ: 'SIGNUP_REQ',
  SHOW_LOGIN_MODAL: 'SHOW_LOGIN_MODAL',
  HIDE_LOGIN_MODAL: 'HIDE_LOGIN_MODAL',
  FETCH_RESTAURANTS_REQ: 'FETCH_RESTAURANTS_REQ',
  FETCH_RESTAURANT_REQ: 'FETCH_RESTAURANT_REQ',
  ORDER_REQ: 'ORDER_REQ',
  INIT_ORDER_REQ: 'INIT_ORDER_REQ',
  SEARCH_RESTAURANTS: 'SEARCH_RESTAURANTS',
};
